### ISSUE TITLE
Will the codes for attacking voxel-based detection model be publicly available?

### ISSUE THREAD

**Issue by nowangry** [WUSTL-CSPL/SlowLiDAR#1]
Hello, thanks for sharing! 
The codes for targeting a BEV-based detector, i.e., PIXOR were provided in the project. I would like to inquire that, will the codes for attacking voxel-based detection models be publicly available, too ? Thanks a lot !!

**Comment by MasterEndless** [comment]
Sure, I will consider cleaning up and releasing the code for voxel-based models in the near future, thanks!

**Comment by ch3ny1** [comment]
Hi there, 

Thanks for the good work! We wanted to follow up on your work but are having difficulty finding the official code for the voxel-based models. 

I wanted to kindly ask if you are still considering releasing that part of the code? It'd be of tremendous help.

Thank you!
