### ISSUE TITLE
in-place problem about " x[:, i, :, :] = x[:, i, :, :] * self.target_std_dev[i] + self.target_mean[i]”

### ISSUE THREAD

**Issue by HansYeoh** [WUSTL-CSPL/SlowLiDAR#2]
Hello, I meet in-place problem and it's located to " x[:, i, :, :] = x[:, i, :, :] * self.target_std_dev[i] + self.target_mean[i]"(in SlowLiDAR/model.py/Decoder). But I check the context and don't think it will result in in-place problem. Thank you very much if you can help me with this！

**Comment by MasterEndless** [comment]
Sorry for the late reply. I found that I could not reproduce the problems you have, could you please provide the detailed environments you run the code? Thanks

**Comment by HansYeoh** [comment]
We found out that it was the wrong version of torch that was causing the problem, this has been solved, thanks for your reply!

**Comment by MasterEndless** [comment]
I am happy to see that your problems have been solved, let me know if you have additional problems, thanks!
